function m(b,a,c,d){b.j.pb(b.tb,a,c,d)}function n(b,a,c,d){b.j.ba?m(b,a,c,d):b.j.Ve()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.j.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Zb||(b.j.Fc(b.ke),b.Zb=!0)}window.jb=class{constructor(b,a){this.j=b;this.tb=a;this.Zb=!1;this.ke=()=>this.Ra()}sc(){}Ra(){}};
window.Gf=class{constructor(){this.qd=-1}l(){-1!==this.qd&&(self.clearTimeout(this.qd),this.qd=-1)}};"use strict";class aa{constructor(b){this.wb=b;this.Xc=!1;this.dd=!0;this.yb=this.ra=this.rd=-1}}
function ba(b,a){const c=a.elementId,d=b.uc(c,a),e=new aa(d);b.Ka.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.dd=!!a.isVisible;var f=b.Ic(d);f.addEventListener("focus",()=>{x(b,"elem-focused",c)});f.addEventListener("blur",()=>{x(b,"elem-blurred",c)});f=a.htmlIndex;e.rd=f;e.yb=a.htmlZIndex;b.Ua&&(a=b.j.wc(f),e.ra=a,b.j.Ob(a).appendChild(d))}function ca(b,a,c){q(b,a,d=>{const e=y(b,d.elementId);return c(e,d)})}
function y(b,a){b=b.Ka.get(a);if(!b)throw Error(`no element with id ${a}`);return b.wb}function x(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}function z(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.Nb=class extends self.jb{constructor(b,a){super(b,a);this.Ka=new Map;this.Ua=!0;v(this,[["create",c=>ba(this,c)],["destroy",c=>{c=c.elementId;const d=y(this,c);this.Ua&&d.parentElement.removeChild(d);this.Ka.delete(c)}],["set-visible",c=>{if(this.Ua){var d=this.Ka.get(c.elementId),e=d.wb;d.Xc?e.style.display=c.isVisible?"":"none":d.dd=!!c.isVisible}}],["update-position",c=>{if(this.Ua){var d=this.Ka.get(c.elementId),e=d.wb,f=this.j;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.rd=g;g=f.wc(g);g!==d.ra&&(e.remove(),f.Ob(g).appendChild(e),d.ra=g,f.Rc());c=c.htmlZIndex;c!==d.yb&&(d.yb=c,f.Rc());d.Xc||(d.Xc=!0,d.dd&&(e.style.display=""))}}],["update-state",c=>{const d=y(this,c.elementId);this.qb(d,c)}],["focus",c=>this.Oc(c)],["set-css-style",c=>{const d=y(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",
c=>{y(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{y(this,c.elementId).removeAttribute(c.name)}]]);ca(this,"get-element",c=>c)}uc(){throw Error("required override");}qb(){throw Error("required override");}Ic(b){return b}Oc(b){const a=this.Ic(y(this,b.elementId));b.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),A=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let ha=0;function ia(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.wf?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.Af+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ja(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ka={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const na=[];let C=0;window.RealFile=window.File;const E=[],oa=new Map,qa=new Map;let ua=0;const va=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");va.push(b)};const wa=new Set(["cordova","playable-ad","instant-games"]);let xa=!1;
window.pa=class b{constructor(a){this.ba=a.Cf;this.za=null;this.aa="";this.eb=a.zf;this.Lb={};this.Ya=this.wa=null;this.Wa=[];this.ma=null;this.Yd=!0;this.M=[];this.kd=[];this.ld=!1;this.le=()=>this.Te();this.ad=!1;this.Sd=0;this.Ab=null;this.cb=-1;this.sf=()=>this.df();this.Ib=new Set;this.sd=null;this.me=[];this.u=a.ne;this.$b="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.ba=!1;fa&&(this.ba=!1);if("cordova"===this.u&&this.ba&&A){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.oa()?self.chrome.webview.addEventListener("message",c=>this.Id(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Id(c));this.cc=this.ta=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.hf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Ze());this.B("runtime","cordova-fetch-local-file",c=>this.$e(c));this.B("runtime","create-job-worker",()=>this.af());this.B("runtime","send-wrapper-extension-message",c=>this.gf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Gd(a)):this.Gd(a)}l(){this.Gc();this.za&&(this.za=this.za.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Ya&&(this.Ya.l(),this.Ya=null);for(const {canvas:a,
hb:c}of this.M)a.remove(),c.remove();this.M.length=0}Fe(){return this.M[0].canvas}wc(a){return Math.min(a,this.M.length-1)}Ob(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].hb}Je(){return da&&"cordova"===this.u}nb(){const a=navigator.userAgent;return da&&wa.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}He(){return A}zd(){return A&&wa.has(this.u)}Bd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}oa(){return this.Bd()||"xbox-uwp-webview2"===this.u}async Gd(a){this.ba&&!await ja()&&(this.ba=!1);"macos-wkwebview"===this.u?this.Ga({type:"ready"}):this.oa()&&(this.kf(),this.me=(await this.Ye()).registeredComponentIds);if("playable-ad"===this.u){this.ta=self.c3_base64files;this.cc={};await this.Qe();for(let d=0,e=a.gb.length;d<e;++d){var c=a.gb[d];this.cc.hasOwnProperty(c)?a.gb[d]={wf:!0,Af:this.cc[c]}:this.ta.hasOwnProperty(c)&&(a.gb[d]=URL.createObjectURL(this.ta[c]))}a.rc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Fc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.yf?this.aa=a.yf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Ef&&(this.Lb=a.Ef);c=new MessageChannel;this.za=c.port1;this.za.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.cf(d));this.Ab=
new self.Ke(this);await ya(this.Ab);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Xe(a,c.port2):await this.We(a,c.port2)}Jc(a){a=this.Lb.hasOwnProperty(a)?this.Lb[a]:a.endsWith("/workermain.js")&&this.Lb.hasOwnProperty("workermain.js")?this.Lb["workermain.js"]:"playable-ad"===
this.u&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async vc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.$b)return a=await this.Mb(d.vf?a:this.eb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}yc(){return this.oa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.u)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Fd(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ga(),g=this.yc(),
h=window.devicePixelRatio,k=b.mb(),l=a.Kf,p=window.cr_previewImageBlobs||this.ta,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.ne;var ea=(new URLSearchParams(self.location.search)).has("debug"),G=this.Ab;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:ea,
ife:!!self.Jf,jobScheduler:{inputPort:G.$c,outputPort:G.jd,maxNumWorkers:G.pf},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.eb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.eb+"opus.wasm.wasm",isFileProtocol:this.$b,isiOSCordova:this.Je(),isiOSWebView:this.nb(),isWindowsWebView2:this.Bd(),isAnyWebView2Wrapper:this.oa(),wrapperComponentIds:this.me,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Xe(a,c){const d=this.Jc(a.Df);"preview"===
this.u?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.wa.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.wa.addEventListener("message",r);this.wa.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.wa=await this.vc(d,this.aa,{type:"module",name:"Runtime",vf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);
const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,hb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.rc||[],k=a.gb;h=await Promise.all(h.map(l=>this.Sa(l)));k=await Promise.all(k.map(l=>this.Sa(l)));if("cordova"===this.u)for(let l=0,p=a.qc.length;l<p;++l){const r=a.qc[l],t=r[0];if(t===a.td||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Sa(t)}this.wa.postMessage(Object.assign(this.Fd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.qc,mainProjectScript:a.td,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...za(this.Ab)]);this.Wa=E.map(l=>new l(this));this.Ed();Aa(e);Ba(g);Ca(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.j.Cd(r.tb,"js-invoke-function",{name:l,params:p})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async We(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,hb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wa=E.map(h=>new h(this));this.Ed();Aa(d);Ba(e);e=a.gb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.rc)){var f=[...a.rc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Sa(h)));await Promise.all(e.map(h=>ia(h)));e=self.C3_ProjectScriptsStatus;f=a.td;const g=a.qc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Sa(k),await ia(k),"preview"!==this.u||e[h]||this.Kd(h,"main script did not run to completion")}catch(l){this.Kd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Sa(k),await ia(k);"preview"===this.u&&"object"!==typeof self.Ff.Hf?(this.Tb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Fd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:va}),Ca(this.ma),this.Hd(),this.Ya=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ya,a))}Kd(a,c){this.Tb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Hd(){this.Tb()}Tb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async af(){const a=await Da(this.Ab);return{outputPort:a,transferables:[a]}}hf(a){if(!this.ad){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,hb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Yd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Yd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,hb:p}=this.M.pop();p.remove();this.ba&&!d?this.kd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,Aa(c),Ba(d),this.M.push({canvas:c,hb:d});for(const l of this.Wa)if(l instanceof window.Nb&&l.Ua)for(const p of l.Ka.values())e=l.j.wc(p.rd),f=p.ra,-1!==
e&&-1!==f&&e!==f&&(f=p.wb,f.remove(),l.j.Ob(e).appendChild(f),p.ra=e);this.Rc();return{addedCanvases:a,transferables:k}}Ze(){for(const a of this.kd)a.remove();this.kd.length=0}Rc(){this.ld||(this.ld=!0,this.Fc(this.le))}Te(){this.Jd(this.le);this.ld=!1;let a=[];for(var c of this.Wa)if(c instanceof window.Nb){var d=c.Ua?[...c.Ka.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.ra,l=h.ra;return k!==l?k-l:g.yb-h.yb});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.ra!==c&&(this.Dd(c,a.slice(d,
e)),c=g.ra,d=e)}d<e&&this.Dd(c,a.slice(d,e))}Dd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.wb);var d=new Set(c);a=this.Ob(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Ve(){if(this.ba)throw Error("not available in worker mode");return this.Ya}pb(a,c,d,e,f){this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Cd(a,c,d,e,f){const g=ua++,h=new Promise((k,l)=>{qa.set(g,{resolve:k,reject:l})});this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.bf(a);if("result"===c)this.ef(a);else if("runtime-ready"===c)this.ff();else if("alert-error"===c)this.Tb(),alert(a.message);else if("creating-runtime"===c)this.Hd();else throw Error(`unknown message '${c}'`);}bf(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=oa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Sb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Sb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Sb(f,!1,""+h)}):this.Sb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Sb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.za.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}ef(a){const c=a.responseId,d=a.isOk;a=a.result;const e=qa.get(c);d?e.resolve(a):e.reject(a);qa.delete(c)}B(a,c,d){let e=oa.get(a);e||(e=new Map,oa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Oa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ed(){for(const a of this.Wa)if("runtime"===a.tb){this.ma=a;return}throw Error("cannot find runtime DOM handler");
}cf(a){this.pb("debugger","message",a)}ff(){for(const a of this.Wa)a.sc()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||xa)}static Ub(a){xa=!!a}Fc(a){this.Ib.add(a);this.Qc()}Jd(a){this.Ib.delete(a);0===this.Ib.size&&this.Gc()}Qc(){-1===this.cb&&0<this.Ib.size&&(this.cb=requestAnimationFrame(this.sf))}Gc(){-1!==this.cb&&(cancelAnimationFrame(this.cb),this.cb=-1)}df(){this.cb=-1;for(const a of this.Ib)a();this.Qc()}Fa(a){this.ma.Fa(a)}Qa(a){this.ma.Qa(a)}Pc(){this.ma.Pc()}Rb(a){this.ma.Rb(a)}Ie(){return!!ka["audio/webm; codecs=opus"]}async lf(a){a=
await this.Cd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Me(a){this.ad=!0;this.Sd=a}Ge(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Ad(a){return!this.Ge(a)}async Sa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.$b&&this.Ad(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Mb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async $e(a){const c=a.filename;switch(a.as){case "text":return await this.Ee(c);
case "buffer":return await this.Mb(c);default:throw Error("unsupported type");}}xd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ee(a){a=await this.xd(a);return await la(a)}Hc(){if(na.length&&!(8<=C)){C++;var a=na.shift();this.Re(a.filename,a.Bf,a.uf)}}Mb(a){return new Promise((c,d)=>{na.push({filename:a,Bf:e=>{C--;this.Hc();c(e)},uf:e=>{C--;this.Hc();d(e)}});this.Hc()})}async Re(a,c,d){try{const e=
await this.xd(a),f=await ma(e);c(f)}catch(e){d(e)}}Id(a){if("entered-fullscreen"===a)b.Ub(!0),F(this.ma);else if("exited-fullscreen"===a)b.Ub(!1),F(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.sd(a),this.sd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}gf(a){this.Ga({type:"extension-message",componentId:a.componentId,messageId:a.messageId,
params:a.params||[],asyncId:a.asyncId})}Ga(a){this.oa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}kf(){window.moveTo=(a,c)=>{this.Ga({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ga({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ye(){return this.oa()?new Promise(a=>{this.sd=a;this.Ga({type:"wrapper-init"})}):
Promise.resolve()}async Qe(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.Pe(c,d));await Promise.all(a)}async Pe(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.cc[a]=c.str;else{let d=await this.Ue(c);d||(d=this.Se(c));this.ta[a]=d}}async Ue(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Se(a){a=this.jf(a);return this.Oe(a.data,a.xf)}jf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{xf:a,data:d}}Oe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.pa,Ea=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Fa={dispatchUserScriptEvent:!0},Ga={dispatchRuntimeEvent:!0};function Ha(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ia(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ja(b){b=URL.createObjectURL(b);try{return await Ia(b)}finally{URL.revokeObjectURL(b)}}function Ka(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const La=new Set(["input","textarea","datalist","select"]),Ma=new Set(["canvas","body","html"]);
function J(b){b.target.tagName&&Ma.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Na(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Oa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ja(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ja(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Pa=!1;document.addEventListener("pause",()=>Pa=!0);document.addEventListener("resume",()=>Pa=!1);function Aa(b){b.addEventListener("selectstart",J);b.addEventListener("gesturehold",J);b.addEventListener("pointerdown",J)}function Ba(b){b.addEventListener("selectstart",Na);b.addEventListener("gesturehold",Na);b.addEventListener("touchstart",Na)}function Ca(b){b.Rd=!0;b.ed=b.j.qa();b.Bb=b.j.ga()}
function F(b){if(!b.ka){var a=H.mb();a&&"any"!==b.od&&Qa(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ga()})}}async function Ra(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Sa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ta(b){return await self.C3_GetSvgImageSize(b.blob)}function Ua(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Va(b){self.setTimeout(()=>{b.Qd=!0},1E3);"cordova"===b.j.u?(document.addEventListener("pause",()=>Wa(b,!0)),document.addEventListener("resume",()=>Wa(b,!1))):document.addEventListener("visibilitychange",()=>Wa(b,"hidden"===document.visibilityState));b.hc=!("hidden"!==document.visibilityState&&!Pa);return{isSuspended:b.hc}}
function Xa(b){b.Md||(b.Md=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ya(b){b.Ld||(b.Ld=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Za(b){await Ha(b.url)}
function $a(b,a){b.Td=a.message;-1===b.Vc&&(b.Vc=setTimeout(()=>{b.Vc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Td)},250))}function ab(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:H.mb(),innerWidth:b.qa(),innerHeight:b.ga()})}
function Wa(b,a){b.hc!==a&&((b.hc=a)?b.j.Gc():b.j.Qc(),m(b,"visibilitychange",{hidden:a}),!a&&b.j.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function bb(b,a,c){"Backspace"===c.key&&J(c);"nwjs"===b.j.u&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ka){var d=Ea.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function K(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function L(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.gd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&
(b.gd=c.buttons)}}function cb(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ca=a))}}
function db(b,a,c,d){const e=b.qa(),f=b.ga();b.fb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.mb(),cssDisplayMode:b.j.yc()}):10>d&&eb(b,e,f,d+1)}function eb(b,a,c,d){-1!==b.fb&&clearTimeout(b.fb);b.fb=setTimeout(()=>db(b,a,c,d),48)}
function Qa(b){b=b.od;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function fb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Oa(class extends self.jb{constructor(b){super(b,"runtime");this.Rd=!1;this.fb=-1;this.od="any";this.hc=this.Ld=this.Md=!1;this.nc=document.createElement("div");this.nc.className="c3-screen-reader-text";this.nc.setAttribute("aria-live","polite");document.body.appendChild(this.nc);this.Ja=null;this.ka=!1;this.Td="";this.Vc=-1;this.Qd=!1;this.ed=b.qa();this.Bb=b.ga();this.Ca=this.Kb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ra(c));b.B("runtime","raster-svg-image",c=>Sa(c));b.B("runtime","get-svg-image-size",c=>Ta(c));b.B("runtime","set-target-orientation",c=>{this.od=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ua(c));b.B("runtime","go-to-script",c=>Ua(c));b.B("runtime","before-start-ticking",()=>Va(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ja||(this.Ja=document.createElement("div"),this.Ja.id="inspectOutline",document.body.appendChild(this.Ja));var d=this.Ja;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ja&&(this.Ja.style.display="none")});b.B("runtime","enable-device-orientation",()=>Xa(this));b.B("runtime","enable-device-motion",()=>Ya(this));b.B("runtime","add-stylesheet",c=>Za(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Mc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.nc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.j.Fe().style.display="";this.j.Me(c.duration)});b.B("runtime","export-to-video-progress",c=>$a(this,c));b.B("runtime","exported-to-video",c=>{window.tf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.tf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ka(d)||c.preventDefault()});window.addEventListener("selectstart",J);window.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});window.addEventListener("pointerdown",J,{passive:!1});this.gd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Oa,{passive:!1});window.addEventListener("wheel",Oa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Rd){var c=this.qa();var d=this.ga();if(this.j.zd()){if(this.Qd){if(this.ed===
c&&d<this.Bb){this.Kb=this.Bb-d;cb(this,this.Bb,this.Kb);c=void 0;break a}0<this.Kb&&(this.Kb=0,cb(this,d,this.Kb))}this.ed=c;this.Bb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.mb(),cssDisplayMode:this.j.yc()});this.j.nb()&&(-1!==this.fb&&clearTimeout(this.fb),db(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>F(this));window.addEventListener("webkitfullscreenchange",()=>F(this));window.addEventListener("mozfullscreenchange",
()=>F(this));window.addEventListener("fullscreenerror",c=>ab(this,c));window.addEventListener("webkitfullscreenerror",c=>ab(this,c));window.addEventListener("mozfullscreenerror",c=>ab(this,c));if(b.nb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Za=new Set;this.ec=new WeakSet;this.ya=!1}sc(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Ga)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Ga);this.gd=0});window.addEventListener("focusin",a=>{a=a.target;(La.has(a.tagName.toLowerCase())||Ka(a))&&m(this,"keyboard-blur",null,Ga)});window.addEventListener("keydown",a=>bb(this,"keydown",a));window.addEventListener("keyup",a=>bb(this,"keyup",a));window.addEventListener("mousedown",a=>K(this,"mousedown",a,
Fa));window.addEventListener("mousemove",a=>K(this,"mousemove",a,Fa));window.addEventListener("mouseup",a=>K(this,"mouseup",a,Fa));window.addEventListener("dblclick",a=>K(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ca,pageX:a.pageX,pageY:a.pageY+this.Ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
fb(a.target)&&document.activeElement&&!fb(document.activeElement)&&document.activeElement.blur();L(this,"pointerdown",a)});this.j.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{L(this,"pointermove",a)}):window.addEventListener("pointermove",a=>L(this,"pointermove",a));window.addEventListener("pointerup",a=>L(this,"pointerup",a));window.addEventListener("pointercancel",a=>L(this,"pointercancel",a));const b=()=>this.Pc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.j.He()&&!this.j.zd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{cb(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.j.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.j.qa()}ga(){return this.j.ga()}Pc(){var b=
[...this.Za];this.Za.clear();if(!this.ya)for(const a of b)(b=a.play())&&b.catch(()=>{this.ec.has(a)||this.Za.add(a)})}Fa(b){if("function"!==typeof b.play)throw Error("missing play function");this.ec.delete(b);let a;try{a=b.play()}catch(c){this.Za.add(b);return}a&&a.catch(()=>{this.ec.has(b)||this.Za.add(b)})}Qa(b){this.Za.delete(b);this.ec.add(b)}Rb(b){this.ya=!!b}Mc(b){alert(b.message)}});"use strict";
async function ya(b){if(b.mf)throw Error("already initialised");b.mf=!0;var a=b.Aa.Jc(("playable-ad"===b.Aa.u?b.Aa.eb:"")+"dispatchworker.js");b.Uc=await b.Aa.vc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.$c=a.port1;b.Uc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.jd=await Da(b)}function za(b){return[b.$c,b.jd]}
async function Da(b){const a=b.Zd.length;var c=b.Aa.Jc(("playable-ad"===b.Aa.u?b.Aa.eb:"")+"jobworker.js");c=await b.Aa.vc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Uc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Zd.push(c);return e.port1}
self.Ke=class{constructor(b){this.Aa=b;this.sb=b.aa;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.eb;this.pf=Math.min(navigator.hardwareConcurrency||2,16);this.Uc=null;this.Zd=[];this.jd=this.$c=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.pa({Cf:!1,Df:"workermain.js",gb:["scripts/c3runtime.js"],qc:[],td:"",zf:"scripts/",rc:[],ne:"html5"}));"use strict";
async function gb(b,a){a=a.type;let c=!0;0===a?c=await hb():1===a&&(c=await kb());m(b,"permission-result",{type:a,result:c})}async function hb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function kb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.pa.Oa(class extends self.jb{constructor(b){super(b,"touch");q(this,"request-permission",a=>gb(this,a))}});"use strict";function M(b){b.stopPropagation()}function lb(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.pa.Oa(class extends self.Nb{constructor(b){super(b,"text-input");ca(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}uc(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",M);c.addEventListener("pointermove",M);c.addEventListener("pointerrawupdate",M);c.addEventListener("pointerup",M);c.addEventListener("mousedown",
M);c.addEventListener("mouseup",M);c.addEventListener("keydown",lb);c.addEventListener("keyup",lb);c.addEventListener("click",e=>{e.stopPropagation();z(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();z(this,"dblclick",b)});c.addEventListener("input",()=>x(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.qb(c,a);return c}qb(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";const mb=180/Math.PI;
async function nb(b,a){if(a.isiOSCordova||a.isSafari)b.jc=!0;b.pd=a.timeScaleMode;b.de=["equalpower","HRTF","soundfield"][a.panningModel];b.Pd=["linear","inverse","exponential"][a.distanceModel];b.ee=a.refDistance;b.ce=a.maxDistance;b.ge=a.rolloffFactor;if(b.j.ad)b.jc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.j.Sd)});else{var c={latencyHint:a.latencyHint};b.je||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ob(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ob(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Va=b.g.createGain();b.Va.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>N(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function pb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.$d=g.slice(0);qb(b,g);try{b.R=await rb(b,c,d,e,g,f);if(p){O(b.R,!0);var u=b.R,ea=p.x,G=p.y,Hb=p.z,Ib=p.angle,ra=p.innerAngle,sa=p.outerAngle,ta=p.outerGain;if(u.zb){sb(u,ea,G,Hb,Ib);var D=self.ib.Ne;
u.ua[0]!==D(ra)&&(u.ua[0]=D(ra),u.F.coneInnerAngle=D(ra));u.ua[1]!==D(sa)&&(u.ua[1]=D(sa),u.F.coneOuterAngle=D(sa));u.ua[2]!==ta&&(u.ua[2]=ta,u.F.coneOuterGain=ta)}p.hasOwnProperty("uid")&&(b.R.sa=p.uid)}else"number"===typeof r&&0!==r?(P(b.R,!0),tb(b.R,r)):(O(b.R,!1),P(b.R,!1));b.R.Play(h,k,l,t)}catch(Jb){console.error("[Construct] Audio: error starting playback: ",Jb);return}finally{c=g.join(" ");d=b.Hb.get(c);if(!d)throw Error("expected pending tag");d.ud--;0===d.ud&&(d.resolve(),b.Hb.delete(c))}w(b)}
async function ub(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await vb(b,c);for(const h of Q(b,c))if(!h.xa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Na=d;h.Xa=g;h.ie=a}R(b)}async function wb(b,a){const c=a.tags;a=a.rate;await vb(b,c);for(const d of Q(b,c))d.la!==a&&(d.la=a,d.Ha())}async function xb(b,a){const c=a.tags;a=a.pos;await vb(b,c);for(const d of Q(b,c))d.Cc(a)}
async function yb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await rb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function zb(b,a){if(a=await N(b,"",a.url,a.type,a.isMusic,!0))a.l(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function Ab(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await N(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.te(b,...e);else if("delay"===c)d=new self.re(b,...e);else if("convolution"===c){var g=d=new self.qe(b,f.ha,...e),h=a.bufferType;g.Nd=a.bufferOriginalUrl;g.Od=h}else if("flanger"===c)d=
new self.ue(b,...e);else if("phaser"===c)d=new self.we(b,...e);else if("gain"===c)d=new self.ve(b,...e);else if("stereopan"===c)d=new self.ye(b,...e);else if("tremolo"===c)d=new self.ze(b,...e);else if("ringmod"===c)d=new self.xe(b,...e);else if("distortion"===c)d=new self.se(b,...e);else if("compressor"===c)d=new self.pe(b,...e);else if("analyser"===c)d=new self.oe(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Xd=l.length;d.nd=
h;l.push(d);Bb(g,h)}Cb(b)}
async function Db(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Da()&&1===c||!e.Da()&&2===c?d.push(e):e.l();b.H=d}for(const f of b.ja.values())for(const g of f)g.l();b.ja.clear();b.oc=a.timeScale;b.Wc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.ya=a.isSilent;b.j.Rb(b.ya);b.dc=a.masterVolume;b.Va.gain.value=
b.dc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Ab(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Eb(b,f,c)));R(b)}
async function Fb(b,a){try{const c=b.g.suspend(a.time);b.Wd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.j.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Gb(d)),b.Wd=!0);await c}catch(c){Gb(c)}}
function ob(b){b.Yb||(b.Zc=!1,window.addEventListener("pointerup",b.Ba,!0),window.addEventListener("touchend",b.Ba,!0),window.addEventListener("click",b.Ba,!0),window.addEventListener("keydown",b.Ba,!0),b.Yb=!0)}
async function N(b,a,c,d,e,f){for(var g of b.ia)if(g.lb()===c)return await Kb(g),g;if(f)return null;if(e&&(b.jc||b.Vd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Da()?g.l():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.je;e&&f&&(b.Vd=!0);c=!e||b.jc||f?new self.Ce(b,a,c,d,e,f):new self.Ae(b,a,c,d,e);b.ia.push(c);await Kb(c);b.be.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.be.add(a));return c}
function Lb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Mb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function Bb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Ob(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.La&&b.fd===a&&(b.La.disconnect(),b.La.connect(c))}
function*Ob(b,a){if(a)for(const c of b.H)Lb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Pb(b,a,c){return c?b.j.lf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Qb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.l():++c}b.H.length=c}
function*Q(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Lb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function rb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.tc()||f))return g.na=e,g;a=await N(b,a,c,d,f);e="html5"===a.Sc?new self.Be(a.v,a,e):new self.De(a.v,a,e);b.H.push(e);return e}
function qb(b,a){a=a.join(" ");let c=b.Hb.get(a);if(!c){let d=null;c={ud:0,promise:new Promise(e=>d=e),resolve:d};b.Hb.set(a,c)}c.ud++}function vb(b,a){return(b=b.Hb.get((0===a.length?b.$d:a).join(" ")))?b.promise:Promise.resolve()}function R(b){if(0<b.Ta.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Rb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function Cb(b){b.bd||(b.bd=!0,Promise.resolve().then(()=>Sb(b)))}
function Sb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.bd=!1}
async function Eb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await rb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(O(b,!0),e=b.F,f=d.pos,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],f=d.orient,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],e.setPosition(...b.ab),e.setOrientation(...b.$a),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):O(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?P(b,!1):(P(b,!0),tb(b,d));c.Play(k,l,p,0);a.isPlaying||c.ob();c.Lc(a)}}}function Gb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ib=class extends self.jb{constructor(b){super(b,"audio");this.Va=this.g=null;this.Yb=this.Zc=!1;this.Ba=()=>{if(!this.Zc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Yb&&(this.Zc=!0,window.removeEventListener("pointerup",this.Ba,!0),window.removeEventListener("touchend",this.Ba,!0),window.removeEventListener("click",this.Ba,!0),window.removeEventListener("keydown",
this.Ba,!0),this.Yb=!1)}};this.ia=[];this.H=[];this.R=null;this.$d=[];this.be=new Set;this.ae=-1;this.Hb=new Map;this.dc=1;this.ya=!1;this.pd=0;this.oc=1;this.Wc=0;this.de="HRTF";this.Pd="inverse";this.ee=600;this.ce=1E4;this.ge=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Vd=this.jc=!1;this.je=this.j.Ie();this.ja=new Map;this.Ta=new Set;this.Wd=this.bd=!1;this.fd="";this.La=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.La&&this.La.disconnect();this.fd=c.toLowerCase();this.La=this.g.createMediaStreamSource(a);
this.La.connect(Mb(this,this.fd))};this.Xb=null;self.C3Audio_GetOutputStream=()=>{this.Xb||(this.Xb=this.g.createMediaStreamDestination(),this.Va.connect(this.Xb));return this.Xb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>nb(this,a)],["play",a=>pb(this,a)],["stop",a=>{a=a.tags;for(const c of Q(this,a))c.Ea()}],["stop-all",()=>{for(const a of this.H)a.Ea()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of Q(this,c))a?d.ob():d.Qb();R(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of Q(this,c))S(d,a)}],["fade-volume",a=>ub(this,a)],["set-master-volume",a=>{this.dc=a.vol;this.Va.gain.value=this.dc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of Q(this,c))Tb(d,a)}],["set-silent",a=>{this.ya=a.isSilent;this.j.Rb(this.ya);for(const c of this.H)c.Vb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of Q(this,c))d.Dc(a)}],["set-playback-rate",a=>wb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of Q(this,
c))P(d,!0),tb(d,a)}],["seek",a=>xb(this,a)],["preload",a=>yb(this,a)],["unload",a=>zb(this,a)],["unload-all",()=>{for(const a of this.ia)a.l();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ec(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Ab(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Cb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.l();this.ja.delete(a);Bb(this,a)}}],["tick",a=>{this.oc=a.timeScale;this.Wc=a.gameTime;this.ae=a.tickCount;if(0!==this.pd)for(var c of this.H)c.Ha();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&sb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Db(this,a)],["offline-render-audio",a=>Fb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Va}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Pb(){return this.ya}Fa(b){this.j.Fa(b)}Qa(b){this.j.Qa(b)}Ra(){for(var b of this.Ta)b.Ra();
b=this.g.currentTime;for(var a of this.H)a.Ra(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.ae,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ta].map(c=>({tag:c.nd,index:c.Xd,peak:c.bb,rms:c.fe,binCount:c.m.frequencyBinCount,freqBins:c.Ud}))});0===a.length&&0===this.Ta.size&&this.Zb&&(this.j.Jd(this.ke),this.Zb=!1)}static Ne(b){return b*mb}static yd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Le(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.pa.Oa(self.ib);"use strict";function Kb(b){b.bc||(b.bc=b.Kc());return b.bc}self.vd=class{constructor(b,a,c,d,e){this.v=b;this.rf=a;this.Ma=c;this.T=d;this.nf=e;this.Sc="";this.bc=null}l(){this.bc=this.v=null}Kc(){}V(){return this.v.V()}zc(){return this.rf}lb(){return this.Ma}xc(){return this.T}Da(){return this.nf}fa(){}};"use strict";
self.Ae=class extends self.vd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Sc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Cb=this.Db=null;this.L.addEventListener("canplaythrough",()=>!0);this.Gb=this.V().createGain();this.Fb=null;this.L.addEventListener("canplay",()=>{this.Db&&(this.Db(),this.Cb=this.Db=null);!this.Fb&&this.L&&(this.Fb=this.V().createMediaElementSource(this.L),this.Fb.connect(this.Gb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ma}' error: `,f);this.Cb&&(this.Cb(f),this.Cb=this.Db=null)})}l(){Qb(this.v,this);this.Gb.disconnect();this.Gb=null;this.Fb.disconnect();this.Fb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.l()}Kc(){return new Promise((b,a)=>{this.Db=b;this.Cb=a;this.L.src=this.Ma})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Ub(b){if(b.Ia)return b.Ia;var a=b.v.j;if("cordova"===a.u&&a.Ad(b.Ma)&&a.$b)b.Ia=await a.Mb(b.Ma);else{a=await fetch(b.Ma);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ia=await a.arrayBuffer()}}async function Vb(b){if(b.ha)return b.ha;b.ha=await Pb(b.v,b.Ia,b.qf);b.Ia=null}
self.Ce=class extends self.vd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Sc="webaudio";this.ha=this.Ia=null;this.qf=!!f}l(){Qb(this.v,this);this.ha=this.Ia=null;super.l()}async Kc(){try{await Ub(this),await Vb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ma}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Wb=0;
function O(b,a){a=!!a;b.zb!==a&&(b.zb=a,b.zb?(P(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.de,b.F.distanceModel=b.v.Pd,b.F.refDistance=b.v.ee,b.F.maxDistance=b.v.ce,b.F.rolloffFactor=b.v.ge),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function P(b,a){a=!!a;b.ac!==a&&(b.ac=a,b.ac?(O(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function tb(b,a){b.ac&&b.md!==a&&(b.da.pan.value=a,b.md=a)}function S(b,a){b.Na=a;b.G.gain.cancelScheduledValues(0);b.Xa=-1;b.G.gain.value=b.Ac()}function Tb(b,a){a=!!a;b.xa!==a&&(b.xa=a,b.Vb())}
function sb(b,a,c,d,e){if(b.zb){var f=b.ab,g=b.$a,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function T(b){return b.cd?b.v.Wc:performance.now()/1E3}
self.wd=class{constructor(b,a,c){this.v=b;this.P=a;this.na=c;this.Wb=Wb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.zb=!1;this.ab=[0,0,0];this.$a=[0,0,0];this.ua=[0,0,0];this.da=null;this.ac=!1;this.md=0;this.I=!0;this.Y=this.va=this.J=!1;this.Na=1;this.xa=!1;this.la=1;b=this.v.pd;this.cd=1===b&&!this.Da()||2===b;this.Xa=this.sa=-1;this.ie=!1}l(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}ea(){return Mb(this.v,0<this.na.length?this.na[0]:"")}zc(){return this.P.zc()}lb(){return this.P.lb()}xc(){return this.P.xc()}Da(){return this.P.Da()}O(){}tc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Pa(){}fa(){return this.P.fa()}Play(){}Ea(){}ob(){}Qb(){}Ra(b){-1!==this.Xa&&b>=this.Xa&&(this.Xa=-1,this.ie&&this.Ea(),Rb(this.v,"fade-ended",this.na,this.Wb))}Ac(){const b=this.Na;return isFinite(b)?b:0}Pb(){return this.v.Pb()}Vb(){}Dc(){}Ha(){}Cc(){}Ec(){}Bc(){}kb(){var b=
this.Wb,a=this.na,c=this.fa(),d=-1===this.Xa?this.Na:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.ab,orient:this.$a,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Pa(),playbackRate:this.la,uid:this.sa,bufferOriginalUrl:this.zc(),bufferUrl:"",bufferType:this.xc(),isMusic:this.Da(),isLooping:this.Y,isMuted:this.xa,resumePosition:this.Bc(),pan:f,stereoPan:this.da?
this.md:null}}Lc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ha());Tb(this,b.isMuted)}};"use strict";
self.Be=class extends self.wd{constructor(b,a,c){super(b,a,c);this.P.Gb.connect(this.G);this.P.onended=()=>this.Nc()}l(){this.Ea();this.P.Gb.disconnect();super.l()}W(){return this.P.W()}Nc(){this.I=!0;this.sa=-1;Rb(this.v,"ended",this.na,this.Wb)}O(){return this.W().ended}tc(){return this.I?!0:this.O()}Pa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);S(this,a);this.xa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.v.Fa(d);this.J=this.I=!1;this.Y=b;this.la=1}Ea(){const b=this.W();b.paused||b.pause();this.v.Qa(b);this.I=!0;this.J=!1;this.sa=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Qa(b);this.J=!0}}Qb(){!this.J||this.I||this.O()||(this.v.Fa(this.W()),this.J=!1)}Vb(){this.W().muted=this.xa||this.Pb()}Dc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ha(){let b=this.la;this.cd&&(b*=this.v.oc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Cc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}Bc(){return this.Pa()}Ec(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.v.Fa(this.W()),this.va=!1)}};"use strict";
function U(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.rb=null}
self.De=class extends self.wd{constructor(b,a,c){super(b,a,c);this.s=null;this.fc=d=>this.Nc(d);this.Yc=!0;this.rb=null;this.S=this.ic=this.kc=0;this.hd=1}l(){this.Ea();U(this);this.fc=null;super.l()}Nc(b){this.J||this.va||b.target!==this.rb||(this.I=this.Yc=!0,this.sa=-1,U(this),Rb(this.v,"ended",this.na,this.Wb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Yc}tc(){return!this.s||this.I?!0:this.O()}Pa(){let b;b=this.J?this.S:this.ic+(T(this)-this.kc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.xa=!1;this.hd=1;S(this,a);U(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.rb=this.s;this.s.onended=this.fc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Yc=!1;this.Y=b;this.la=1;this.kc=T(this);this.ic=c}Ea(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.sa=-1}ob(){this.J||this.I||this.O()||(this.S=this.Pa(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Qb(){!this.J||this.I||this.O()||(U(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,S(this,this.Na),this.Ha(),this.s.start(0,this.S),this.kc=T(this),this.ic=this.S,this.J=!1)}Ac(){return super.Ac()*this.hd}Vb(){this.hd=this.xa||this.Pb()?0:1;S(this,this.Na)}Dc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ha(){let b=this.la;this.cd&&(b*=this.v.oc);this.s&&(this.s.playbackRate.value=b)}Cc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Qb()))}Bc(){return this.S}Ec(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Pa(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.va=!1:this.va&&(U(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,S(this,this.Na),this.Ha(),this.s.start(0,this.S),this.kc=T(this),this.ic=this.S,this.va=!1)}Lc(b){super.Lc(b);this.S=b.resumePosition}};"use strict";function V(b){return b.g.createGain()}
function W(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class X{constructor(b){this.v=b;this.g=b.V();this.Xd=-1;this.T=this.nd="";this.o=null}l(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.nd,params:this.o}}}
self.te=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=V(this);this.i=V(this);this.i.gain.value=g;this.h=V(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}l(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;W(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;W(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;W(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,W(this,this.D.gain,a,c,d)}}};
self.re=class extends X{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.Eb=V(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=V(this);this.vb.gain.value=c;this.A.connect(this.Eb);this.A.connect(this.h);this.Eb.connect(this.i);this.Eb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Eb)}l(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Eb.disconnect();
this.X.disconnect();this.vb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.ib.yd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);W(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,W(this,this.X.delayTime,a,c,d)}}};
self.qe=class extends X{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Od=this.Nd="";this.A=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i)}l(){this.A.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Nd;b.bufferUrl="";b.bufferType=this.Od;return b}};
self.ue=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=V(this);this.h=V(this);this.h.gain.value=1-f/2;this.i=V(this);this.i.gain.value=f/2;this.xb=V(this);this.xb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=V(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.xb);this.xb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.xb.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;W(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;W(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,W(this,this.xb.gain,a/100,c,d)}}};
self.we=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=V(this);this.h=V(this);this.h.gain.value=1-g/2;this.i=V(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=V(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}l(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;W(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;W(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;W(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;W(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,W(this,this.C.frequency,a,c,d)}}};self.ve=class extends X{constructor(b,a){super(b);this.T="gain";this.o=[a];this.m=V(this);this.m.gain.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){const e=self.ib.yd;switch(b){case 4:this.o[0]=e(a),W(this,this.m.gain,e(a),c,d)}}};
self.ye=class extends X{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.m=this.g.createStereoPanner();this.m.pan.value=a}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,W(this,this.m.pan,a,c,d)}}};
self.ze=class extends X{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.m=V(this);this.m.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=V(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.m.gain);this.C.start(0)}l(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;W(this,this.m.gain,1-a/2,c,d);W(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,W(this,this.C.frequency,a,c,d)}}};
self.xe=class extends X{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=V(this);this.i=V(this);this.i.gain.value=c;this.h=V(this);this.h.gain.value=1-c;this.Jb=V(this);this.Jb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Jb.gain);this.C.start(0);this.A.connect(this.Jb);this.A.connect(this.h);this.Jb.connect(this.i)}l(){this.C.stop(0);this.C.disconnect();this.Jb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,W(this,this.C.frequency,a,c,d)}}};
self.se=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=V(this);this.mc=V(this);this.lc=V(this);b=d;.01>b&&(b=.01);this.mc.gain.value=b;this.lc.gain.value=Math.pow(1/b,.6)*e;this.i=V(this);this.i.gain.value=f;this.h=V(this);this.h.gain.value=1-f;this.pc=this.g.createWaveShaper();this.Tc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Tc[32768+e]=f,this.Tc[32768-
e-1]=-f;this.pc.curve=this.Tc;this.A.connect(this.mc);this.A.connect(this.h);this.mc.connect(this.pc);this.pc.connect(this.lc);this.lc.connect(this.i)}l(){this.A.disconnect();this.mc.disconnect();this.pc.disconnect();this.lc.disconnect();this.i.disconnect();this.h.disconnect();super.l()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,
1-a,c,d)}}};self.pe=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}l(){this.m.disconnect();super.l()}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};
self.oe=class extends X{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.Ud=new Float32Array(this.m.frequencyBinCount);this.he=new Uint8Array(a);this.fe=this.bb=0;b=this.v;b.Ta.add(this);R(b)}l(){this.v.Ta.delete(this);this.m.disconnect();super.l()}Ra(){this.m.getFloatFrequencyData(this.Ud);this.m.getByteTimeDomainData(this.he);const b=this.m.fftSize;let a=this.bb=0;for(var c=0;c<b;++c){let d=(this.he[c]-
128)/128;0>d&&(d=-d);this.bb<d&&(this.bb=d);a+=d*d}c=self.ib.Le;this.bb=c(this.bb);this.fe=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}N(){return this.m}Z(){}};"use strict";function Y(b){b.stopPropagation()}
self.pa.Oa(class extends self.Nb{constructor(b){super(b,"button")}uc(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Y);d.addEventListener("pointermove",
Y);d.addEventListener("pointerrawupdate",Y);d.addEventListener("pointerup",Y);d.addEventListener("mousedown",Y);d.addEventListener("mouseup",Y);d.addEventListener("keydown",Y);d.addEventListener("keyup",Y);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>z(this,"click",b,{isChecked:c.checked}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.qb(d,a);return d}Ic(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}qb(b,a){const c="input"===b.tagName.toLowerCase()?
b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";let Z=null,Xb=null;window.addEventListener("beforeinstallprompt",b=>{b.preventDefault();Z=b;Xb&&m(Xb,"install-available");return!1});function Yb(){}function Zb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function $b(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function ac(){if(!Z)return{result:"unavailable"};try{return Z.prompt(),{result:(await Z.userChoice).outcome}}catch(b){return console.error("[Construct] Requesting install failed: ",b),{result:"failed"}}}
self.pa.Oa(class extends self.jb{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Zb(this)],["alert",a=>this.Mc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Oc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>$b(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.j.oa()?window.open(c,"_blank"):this.If||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.j.oa()||"macos-wkwebview"===this.u)self.pa.Ub(!0),this.j.Ga({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Yb)}}],["exit-fullscreen",()=>{if(this.j.oa()||"macos-wkwebview"===this.u)self.pa.Ub(!1),this.j.Ga({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Yb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>ac()]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}sc(){Z?m(this,"install-available"):Xb=this;window.addEventListener("appinstalled",
()=>{m(this,"app-installed")})}Mc(b){alert(b.message)}Oc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
